Revert "oh actually we can just import it, duh"
This reverts commit 3f975670a83fc33d006c507f83d5d0e17df99219.

Turns out that actually doesn't work either: I think we just *need* to
continue having explicit `zerocopy` deps in embedding crates:

```
error[E0433]: failed to resolve: could not find `zerocopy` in the list of imported crates
   --> /hubris/target/thumbv7em-none-eabihf/release/build/drv-user-leds-api-8a28786152326190/out/client_stub.rs:215:46
    |
215 |         #[derive(zerocopy_derive::IntoBytes, zerocopy_derive::Immutable)]
    |                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `zerocopy` in the list of imported crates
    |
    = note: this error originates in the derive macro `zerocopy_derive::Immutable` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing one of these crates
   --> drv/user-leds-api/src/lib.rs:9:1
    |
9   + use crate::zerocopy;
   --> |drv/user-leds-api/src/lib.rs:9:1
    |
9   + use idol_runtime::zerocopy;
```